#pragma once

static const char INDEX_HTML[] = 
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<title>ESP32-S3-GEEK 极客调试控制台</title>"
"<style>"
":root{"
"  --bg:#090d16;--card:#131b2e;--card-sub:#0b1120;--primary:#0284c7;--primary-hover:#0369a1;"
"  --accent:#38bdf8;--text:#f1f5f9;--sub:#94a3b8;--border:#1e293b;--success:#10b981;"
"  --danger:#ef4444;--purple:#a855f7;--warning:#f59e0b;"
"}"
"*{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}"
"body{background:var(--bg);color:var(--text);display:flex;justify-content:center;min-height:100vh;padding:16px;}"
".container{width:100%;max-width:540px;background:var(--card);border:1px solid var(--border);border-radius:18px;padding:22px;box-shadow:0 24px 48px rgba(0,0,0,0.6);margin:auto;}"
".header{display:flex;align-items:center;gap:12px;margin-bottom:16px;border-bottom:1px solid var(--border);padding-bottom:14px;}"
".icon{width:42px;height:42px;background:linear-gradient(135deg,#0284c7,#a855f7);border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:bold;font-size:22px;}"
".title h1{font-size:17px;font-weight:700;color:#fff;letter-spacing:0.5px;}"
".title p{font-size:11px;color:var(--sub);margin-top:2px;}"
".tabs{display:flex;gap:4px;margin-bottom:16px;background:var(--card-sub);padding:4px;border-radius:12px;border:1px solid var(--border);overflow-x:auto;}"
".tab-btn{flex:1;min-width:70px;padding:8px 6px;background:none;border:none;color:var(--sub);border-radius:8px;font-size:12px;font-weight:600;cursor:pointer;transition:all .2s;white-space:nowrap;text-align:center;}"
".tab-btn.active{background:var(--primary);color:#fff;box-shadow:0 2px 10px rgba(2,132,199,0.4);}"
".tab-content{display:none;}"
".tab-content.active{display:block;}"
".card{background:var(--card-sub);border:1px solid var(--border);border-radius:10px;padding:12px;margin-bottom:14px;}"
".card-title{font-size:13px;font-weight:600;color:var(--accent);margin-bottom:8px;display:flex;align-items:center;gap:6px;}"
".status-row{display:flex;justify-content:space-between;align-items:center;font-size:12px;padding:3px 0;}"
".badge{padding:2px 8px;border-radius:99px;font-size:11px;font-weight:600;}"
".badge-ap{background:#0369a1;color:#e0f2fe;}"
".badge-sta{background:#047857;color:#d1fae5;}"
".badge-purple{background:#7e22ce;color:#f3e8ff;}"
".badge-fail{background:#b91c1c;color:#fee2e2;}"
".badge-warn{background:#b45309;color:#fef3c7;}"
".form-group{margin-bottom:12px;}"
"label{display:block;font-size:12px;color:var(--sub);margin-bottom:5px;font-weight:500;}"
"input,select,textarea{width:100%;padding:9px 12px;background:#060a12;border:1px solid var(--border);border-radius:8px;color:#fff;font-size:13px;outline:none;transition:border-color .2s;}"
"input:focus,select:focus,textarea:focus{border-color:var(--accent);}"
".row-2{display:grid;grid-template-columns:1fr 1fr;gap:10px;}"
".row-check{display:flex;align-items:center;gap:8px;font-size:13px;color:var(--text);cursor:pointer;margin:8px 0;}"
".row-check input{width:auto;cursor:pointer;}"
".btn{width:100%;padding:10px;background:var(--primary);color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;transition:all .2s;display:flex;justify-content:center;align-items:center;gap:6px;}"
".btn:hover{background:var(--primary-hover);}"
".btn:disabled{opacity:0.5;cursor:not-allowed;}"
".btn-scan{background:#1e293b;color:var(--accent);border:1px solid #334155;margin-bottom:10px;padding:8px;}"
".btn-purple{background:var(--purple);}"
".btn-purple:hover{background:#9333ea;}"
".btn-danger{background:var(--danger);}"
".btn-danger:hover{background:#dc2626;}"
".btn-warning{background:var(--warning);color:#000;}"
".btn-warning:hover{background:#d97706;}"
".terminal{background:#040711;border:1px solid #1e293b;border-radius:8px;height:240px;padding:10px;overflow-y:auto;font-family:monospace;font-size:12px;color:#38bdf8;line-height:1.45;white-space:pre-wrap;word-break:break-all;margin-bottom:10px;}"
".term-ctrl{display:flex;gap:6px;}"
".term-btn{padding:8px 12px;background:#1e293b;color:#f1f5f9;border:1px solid #334155;border-radius:6px;font-size:12px;cursor:pointer;white-space:nowrap;}"
".term-btn:hover{background:#334155;}"
".log-table{width:100%;border-collapse:collapse;margin-top:6px;font-size:12px;}"
".log-table th,.log-table td{padding:8px 6px;text-align:left;border-bottom:1px solid var(--border);}"
".log-table th{color:var(--sub);font-weight:500;font-size:11px;}"
".action-btn{padding:3px 7px;border-radius:5px;font-size:11px;font-weight:600;cursor:pointer;text-decoration:none;border:none;display:inline-block;margin-right:3px;}"
".btn-dl{background:#0284c7;color:#fff;}"
".btn-view{background:#334155;color:#e2e8f0;}"
".btn-del{background:#991b1b;color:#fecaca;}"
".modal{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.75);z-index:99;justify-content:center;align-items:center;padding:16px;}"
".modal.show{display:flex;}"
".modal-card{width:100%;max-width:620px;background:var(--card);border:1px solid var(--border);border-radius:14px;padding:16px;max-height:85vh;display:flex;flex-direction:column;}"
".modal-title{font-size:14px;font-weight:600;margin-bottom:8px;display:flex;justify-content:space-between;align-items:center;}"
".modal-body{background:#060a12;border:1px solid var(--border);border-radius:8px;padding:12px;overflow-y:auto;flex:1;font-family:monospace;font-size:12px;white-space:pre-wrap;color:#38bdf8;line-height:1.4;max-height:55vh;}"
".close-btn{background:none;border:none;color:var(--sub);font-size:20px;cursor:pointer;}"
".toast{padding:9px;border-radius:8px;font-size:12px;margin-top:12px;display:none;text-align:center;}"
".toast.show{display:block;}"
".toast-info{background:#075985;color:#e0f2fe;}"
".toast-success{background:#065f46;color:#d1fae5;}"
".toast-danger{background:#991b1b;color:#fee2e2;}"
".footer{margin-top:16px;text-align:center;font-size:11px;color:var(--sub);}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"  <div class='header'>"
"    <div class='icon'>⚡</div>"
"    <div class='title'>"
"      <h1>ESP32-S3-GEEK</h1>"
"      <p>无线调试救援终端 · Web 控制中心</p>"
"    </div>"
"  </div>"
""
"  <div class='tabs'>"
"    <button class='tab-btn active' onclick='switchTab(\"wifi\")'>📶 网络</button>"
"    <button class='tab-btn' onclick='switchTab(\"term\")'>💻 终端</button>"
"    <button class='tab-btn' onclick='switchTab(\"logs\")'>💾 TF日志</button>"
"    <button class='tab-btn' onclick='switchTab(\"hw\")'>⚙️ 参数</button>"
"    <button class='tab-btn' onclick='switchTab(\"sys\")'>⚡ 诊断</button>"
"  </div>"
""
"  <!-- TAB 1: Wi-Fi 与网络配置 -->"
"  <div id='tab-wifi' class='tab-content active'>"
"    <div class='card'>"
"      <div class='card-title'>📡 当前网络状态</div>"
"      <div class='status-row'><span>工作状态:</span><span id='net-badge' class='badge badge-ap'>AP 配网热点</span></div>"
"      <div class='status-row'><span>IP 地址:</span><span id='net-ip' style='color:var(--accent);font-family:monospace;'>192.168.4.1</span></div>"
"      <div class='status-row'><span>已连接 STA:</span><span id='net-ssid' style='color:#fff;'>未连接</span></div>"
"      <div class='status-row'><span>STA MAC:</span><span id='sta-mac' style='color:var(--sub);font-family:monospace;'>--</span></div>"
"      <div class='status-row'><span>AP MAC:</span><span id='ap-mac' style='color:var(--sub);font-family:monospace;'>--</span></div>"
"    </div>"
"    <div class='card'>"
"      <div class='card-title'>🌐 Wi-Fi 连接 (STA 连网)</div>"
"      <button class='btn btn-scan' id='btn-scan' onclick='scanWifi()'>🔍 扫描周边 Wi-Fi 信号</button>"
"      <div class='form-group'>"
"        <label>选择 Wi-Fi (SSID)</label>"
"        <select id='ssid-select' onchange='onSelectSSID(this.value)'><option value=''>-- 点击上方扫描或手动输入 --</option></select>"
"      </div>"
"      <div class='row-2'>"
"        <div class='form-group'><label>Wi-Fi 名称 (SSID)</label><input type='text' id='sta-ssid' placeholder='SSID'></div>"
"        <div class='form-group'><label>Wi-Fi 密码</label><input type='password' id='sta-pwd' placeholder='Password'></div>"
"      </div>"
"      <label class='row-check'><input type='checkbox' id='chk-static' onchange='toggleStaticIP()'> 使用静态 IP (Static IP)</label>"
"      <div id='static-ip-box' style='display:none;margin-top:6px;'>"
"        <div class='row-2'>"
"          <div class='form-group'><label>静态 IP</label><input type='text' id='sta-ip' placeholder='192.168.1.200'></div>"
"          <div class='form-group'><label>子网掩码</label><input type='text' id='sta-mask' value='255.255.255.0'></div>"
"        </div>"
"        <div class='row-2'>"
"          <div class='form-group'><label>默认网关</label><input type='text' id='sta-gw' placeholder='192.168.1.1'></div>"
"          <div class='form-group'><label>首选 DNS</label><input type='text' id='sta-dns' value='8.8.8.8'></div>"
"        </div>"
"      </div>"
"      <button class='btn' id='btn-connect' onclick='saveWifiSTA()'>🚀 保存并连接 STA</button>"
"    </div>"
"    <div class='card'>"
"      <div class='card-title'>📶 本机 AP 热点设置</div>"
"      <div class='row-2'>"
"        <div class='form-group'><label>热点名称 (SSID)</label><input type='text' id='ap-ssid-input' value='GEEK-Debugger'></div>"
"        <div class='form-group'><label>热点密码 (留空开放)</label><input type='password' id='ap-pwd-input' placeholder='至少8位或留空'></div>"
"      </div>"
"      <div class='row-2'>"
"        <div class='form-group'><label>无线信道</label><select id='ap-chan'><option value='1'>Channel 1</option><option value='6' selected>Channel 6</option><option value='11'>Channel 11</option></select></div>"
"        <div class='form-group'><label>最大连接数</label><select id='ap-max'><option value='1'>1</option><option value='2'>2</option><option value='4' selected>4</option></select></div>"
"      </div>"
"      <label class='row-check'><input type='checkbox' id='ap-hidden'> 隐藏热点 SSID</label>"
"      <button class='btn' style='background:#334155;' onclick='saveWifiAP()'>💾 更新热点配置</button>"
"    </div>"
"  </div>"
""
"  <!-- TAB 2: Web 串口交互终端 -->"
"  <div id='tab-term' class='tab-content'>"
"    <div class='card' style='margin-bottom:8px;'>"
"      <div class='status-row'><span>串口波特率:</span><span id='term-baud' style='color:var(--accent);font-family:monospace;'>115200 8N1</span></div>"
"    </div>"
"    <div class='terminal' id='term-box'>[Web Terminal Ready - Connecting to CDC-ACM Stream...]\n</div>"
"    <div class='term-ctrl'>"
"      <input type='text' id='term-input' placeholder='输入调试命令...' onkeydown='if(event.key===\"Enter\")sendTermCmd()'>"
"      <button class='btn' style='width:auto;padding:8px 16px;' onclick='sendTermCmd()'>发送</button>"
"      <button class='term-btn' onclick='sendSpecial(\"\\x03\")'>Ctrl+C</button>"
"      <button class='term-btn' onclick='clearTerm()'>清屏</button>"
"    </div>"
"  </div>"
""
"  <!-- TAB 3: TF 卡会话日志管理 -->"
"  <div id='tab-logs' class='tab-content'>"
"    <div class='card'>"
"      <div class='status-row'><span>TF 卡状态:</span><span id='tf-badge' class='badge badge-purple'>检测中...</span></div>"
"      <div class='status-row'><span>存储容量:</span><span id='tf-cap' style='color:var(--accent);font-family:monospace;'>-- / --</span></div>"
"      <div class='status-row'><span>当前记录会话:</span><span id='tf-cur' style='color:#fff;'>--</span></div>"
"    </div>"
"    <div style='display:flex;gap:8px;margin-bottom:12px;'>"
"      <button class='btn btn-purple' style='flex:2;' onclick='newSession()'>➕ 开启全新 Session</button>"
"      <button class='btn' style='flex:1;background:#334155;' onclick='loadLogs()'>🔄 刷新</button>"
"    </div>"
"    <div style='max-height:260px;overflow-y:auto;border:1px solid var(--border);border-radius:8px;'>"
"      <table class='log-table'>"
"        <thead><tr><th>文件</th><th>大小</th><th>操作</th></tr></thead>"
"        <tbody id='log-tbody'><tr><td colspan='3' style='text-align:center;color:var(--sub);'>正在读取 TF 卡...</td></tr></tbody>"
"      </table>"
"    </div>"
"  </div>"
""
"  <!-- TAB 4: 硬件与外设参数 -->"
"  <div id='tab-hw' class='tab-content'>"
"    <div class='card'>"
"      <div class='card-title'>📺 屏幕与背光设置</div>"
"      <div class='form-group'>"
"        <label>背光亮度: <span id='val-bl' style='color:var(--accent);'>100</span>%</label>"
"        <input type='range' id='cfg-bl' min='10' max='100' value='100' oninput='updateBlText(this.value)' onchange='applyBrightness(this.value)'>"
"      </div>"
"      <div class='row-2'>"
"        <div class='form-group'><label>熄屏超时</label><select id='cfg-timeout'><option value='0'>常亮 (Never)</option><option value='30'>30 秒</option><option value='60'>1 分钟</option><option value='300'>5 分钟</option></select></div>"
"        <div class='form-group'><label>屏幕方向</label><select id='cfg-rot'><option value='0'>默认 (0°)</option><option value='2'>反转 (180°)</option></select></div>"
"      </div>"
"      <button class='btn' style='background:#334155;' onclick='saveDisplayCfg()'>💾 保存显示设置</button>"
"    </div>"
"    <div class='card'>"
"      <div class='card-title'>🔌 串口与 USB 启动模式</div>"
"      <div class='form-group'>"
"        <label>默认 USB 模式</label>"
"        <select id='cfg-usbmode'><option value='0'>复合模式 (CDC-ACM 串口 + CDC-NCM 虚拟网卡)</option><option value='1'>纯串口模式 (Pure Serial CDC-ACM)</option><option value='2'>纯虚拟网卡模式 (Pure Network CDC-NCM)</option></select>"
"      </div>"
"      <div class='row-2'>"
"        <div class='form-group'><label>波特率 (Baudrate)</label><select id='cfg-baud'><option value='9600'>9600</option><option value='19200'>19200</option><option value='38400'>38400</option><option value='57600'>57600</option><option value='115200' selected>115200</option><option value='230400'>230400</option><option value='460800'>460800</option><option value='921600'>921600</option><option value='1500000'>1500000</option><option value='2000000'>2000000</option></select></div>"
"        <div class='form-group'><label>校验位 (Parity)</label><select id='cfg-parity'><option value='0' selected>None (无校验)</option><option value='1'>Odd (奇校验)</option><option value='2'>Even (偶校验)</option></select></div>"
"      </div>"
"      <button class='btn' style='background:#334155;' onclick='saveSerialCfg()'>💾 保存串口设置</button>"
"    </div>"
"    <div class='card'>"
"      <div class='card-title'>💾 TF 卡日志参数</div>"
"      <label class='row-check'><input type='checkbox' id='cfg-log-en' checked> 自动记录全量会话日志</label>"
"      <div class='row-2'>"
"        <div class='form-group'><label>刷盘周期 (Flush)</label><select id='cfg-flush'><option value='100'>100 ms (高实时)</option><option value='300' selected>300 ms (推荐)</option><option value='1000'>1000 ms (省电)</option></select></div>"
"        <div class='form-group'><label>切片限制</label><select id='cfg-maxfile'><option value='0'>不限制</option><option value='1024'>1 MB</option><option value='2048'>2 MB</option><option value='5120'>5 MB</option></select></div>"
"      </div>"
"      <button class='btn' style='background:#334155;' onclick='saveLoggerCfg()'>💾 保存日志参数</button>"
"    </div>"
"  </div>"
""
"  <!-- TAB 5: 系统诊断与控制 -->"
"  <div id='tab-sys' class='tab-content'>"
"    <div class='card'>"
"      <div class='card-title'>⚡ 硬件与固件状态</div>"
"      <div class='status-row'><span>处理器:</span><span id='sys-cpu' style='color:#fff;'>ESP32-S3 @ 240MHz (LX7 双核)</span></div>"
"      <div class='status-row'><span>固件版本:</span><span style='color:var(--accent);font-family:monospace;'>v1.2.0-tf</span></div>"
"      <div class='status-row'><span>SPI Flash:</span><span id='sys-flash' style='color:#fff;'>16 MB (4MB App 分区)</span></div>"
"      <div class='status-row'><span>空闲内存 (Free Heap):</span><span id='sys-heap' style='color:var(--accent);font-family:monospace;'>--</span></div>"
"      <div class='status-row'><span>最低历史内存:</span><span id='sys-minheap' style='color:var(--sub);font-family:monospace;'>--</span></div>"
"      <div class='status-row'><span>系统开机时长:</span><span id='sys-uptime' style='color:#fff;'>--</span></div>"
"    </div>"
"    <div class='card'>"
"      <div class='card-title'>🛠️ 设备维护动作</div>"
"      <div style='display:flex;flex-direction:column;gap:10px;'>"
"        <button class='btn' onclick='doReboot()'>🔄 重启设备 (Reboot)</button>"
"        <button class='btn btn-warning' onclick='doDownloadMode()'>⚡ 一键进入下载模式 (Download Bootloader)</button>"
"        <button class='btn btn-danger' onclick='doFactoryReset()'>🧹 恢复出厂设置 (Wipe NVS)</button>"
"      </div>"
"    </div>"
"  </div>"
""
"  <div class='toast' id='toast'></div>"
"  <div class='footer'><p>ESP32-S3-GEEK Wireless Console Tool · 2026</p></div>"
"</div>"
""
"<!-- 日志查看弹窗 -->"
"<div class='modal' id='modal' onclick='closeModal(event)'>"
"  <div class='modal-card' onclick='event.stopPropagation()'>"
"    <div class='modal-title'><span id='modal-fname'>session.log</span><button class='close-btn' onclick='closeModal()'>&times;</button></div>"
"    <div class='modal-body' id='modal-content'>读取中...</div>"
"  </div>"
"</div>"
""
"<script>"
"let termOffset = 0;"
"let termTimer = null;"
"function showToast(msg,type){const t=document.getElementById('toast');t.className='toast toast-'+type+' show';t.innerText=msg;setTimeout(()=>t.className='toast',4000);}"
"function switchTab(name){"
"  document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));"
"  document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));"
"  const map={wifi:0,term:1,logs:2,hw:3,sys:4};"
"  document.querySelectorAll('.tab-btn')[map[name]].classList.add('active');"
"  document.getElementById('tab-'+name).classList.add('active');"
"  if(name==='term') startTermPolling(); else stopTermPolling();"
"  if(name==='logs') loadLogs();"
"  if(name==='hw'||name==='wifi') loadFullConfig();"
"  if(name==='sys') loadSysInfo();"
"}"
"function toggleStaticIP(){const chk=document.getElementById('chk-static').checked;document.getElementById('static-ip-box').style.display=chk?'block':'none';}"
"function updateBlText(v){document.getElementById('val-bl').innerText=v;}"
"function applyBrightness(v){fetch('/api/config/display',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brightness:parseInt(v)})}).catch(()=>{});}"
"function onSelectSSID(val){if(val){document.getElementById('sta-ssid').value=val;document.getElementById('sta-pwd').focus();}}"
"function scanWifi(){"
"  const b=document.getElementById('btn-scan');b.disabled=true;b.innerText='⏳ 正在扫描 2.4G Wi-Fi...';"
"  fetch('/api/wifi/scan').then(r=>r.json()).then(data=>{"
"    b.disabled=false;b.innerText='🔍 重新扫描';"
"    const s=document.getElementById('ssid-select');s.innerHTML='<option value=\"\">-- 请选择已发现的网络 --</option>';"
"    data.forEach(item=>{"
"      const opt=document.createElement('option');opt.value=item.ssid;opt.innerText=item.ssid+' ('+item.rssi+' dBm)';"
"      s.appendChild(opt);"
"    });"
"  }).catch(e=>{b.disabled=false;b.innerText='🔍 扫描失败，重试';showToast('扫描超时: '+e,'danger');});"
"}"
"function saveWifiSTA(){"
"  const ssid=document.getElementById('sta-ssid').value.trim();"
"  const pwd=document.getElementById('sta-pwd').value;"
"  const isStatic=document.getElementById('chk-static').checked;"
"  if(!ssid){showToast('请输入 Wi-Fi 名称','danger');return;}"
"  const body={"
"    ssid:ssid,password:pwd,static_ip:isStatic,"
"    ip:document.getElementById('sta-ip').value.trim(),"
"    netmask:document.getElementById('sta-mask').value.trim(),"
"    gw:document.getElementById('sta-gw').value.trim(),"
"    dns:document.getElementById('sta-dns').value.trim()"
"  };"
"  const btn=document.getElementById('btn-connect');btn.disabled=true;btn.innerText='正在连接...';"
"  showToast('配置已提交，ESP32 正在尝试连接...','info');"
"  fetch('/api/config/wifi_sta',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})"
"  .then(r=>r.json()).then(res=>{pollStatus();btn.disabled=false;btn.innerText='🚀 保存并连接 STA';})"
"  .catch(e=>{showToast('提交失败: '+e,'danger');btn.disabled=false;btn.innerText='🚀 保存并连接 STA';});"
"}"
"function saveWifiAP(){"
"  const body={"
"    ssid:document.getElementById('ap-ssid-input').value.trim(),"
"    password:document.getElementById('ap-pwd-input').value,"
"    channel:parseInt(document.getElementById('ap-chan').value),"
"    hidden:document.getElementById('ap-hidden').checked,"
"    max_conn:parseInt(document.getElementById('ap-max').value)"
"  };"
"  fetch('/api/config/wifi_ap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})"
"  .then(r=>r.json()).then(res=>{showToast('AP 热点配置已更新！','success');})"
"  .catch(e=>showToast('保存失败: '+e,'danger'));"
"}"
"function pollStatus(){"
"  let count=0;"
"  const timer=setInterval(()=>{"
"    count++;"
"    fetch('/api/wifi/status').then(r=>r.json()).then(st=>{"
"      if(st.state==='CONNECTED'){"
"        clearInterval(timer);"
"        showToast('🎉 连接成功！分配 IP: '+st.ip,'success');"
"        document.getElementById('net-ip').innerText=st.ip;"
"        document.getElementById('net-ssid').innerText=st.ssid;"
"        document.getElementById('net-badge').className='badge badge-sta';"
"        document.getElementById('net-badge').innerText='STA 在线';"
"      }else if(st.state==='FALLBACK'){"
"        clearInterval(timer);"
"        showToast('⚠️ 连接失败，已回退至 AP 模式！','danger');"
"      }"
"    });"
"    if(count>20) clearInterval(timer);"
"  },1500);"
"}"
"function startTermPolling(){"
"  if(termTimer) return;"
"  pollTerm();"
"  termTimer=setInterval(pollTerm,500);"
"}"
"function stopTermPolling(){if(termTimer){clearInterval(termTimer);termTimer=null;}}"
"function pollTerm(){"
"  fetch('/api/terminal/rx?offset='+termOffset).then(r=>r.json()).then(data=>{"
"    if(data.data&&data.data.length>0){"
"      const box=document.getElementById('term-box');"
"      box.innerText+=data.data;"
"      box.scrollTop=box.scrollHeight;"
"    }"
"    termOffset=data.offset;"
"  }).catch(()=>{});"
"}"
"function sendTermCmd(){"
"  const inp=document.getElementById('term-input');"
"  const cmd=inp.value;"
"  if(!cmd) return;"
"  fetch('/api/terminal/tx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:cmd+'\n'})})"
"  .then(()=>{inp.value='';pollTerm();});"
"}"
"function sendSpecial(bytes){"
"  fetch('/api/terminal/tx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:bytes})})"
"  .then(()=>{pollTerm();});"
"}"
"function clearTerm(){document.getElementById('term-box').innerText='';}"
"function loadLogs(){"
"  fetch('/api/logs/list').then(r=>r.json()).then(res=>{"
"    const tb=document.getElementById('log-tbody');"
"    const tfb=document.getElementById('tf-badge');"
"    if(!res.mounted){"
"      tfb.className='badge badge-fail';tfb.innerText='未插入 TF 卡';"
"      document.getElementById('tf-cap').innerText='--';"
"      document.getElementById('tf-cur').innerText='--';"
"      tb.innerHTML='<tr><td colspan=\"3\" style=\"text-align:center;color:var(--sub);padding:20px;\">未检测到 MicroSD 卡，请插入后刷新</td></tr>';"
"      return;"
"    }"
"    tfb.className='badge badge-purple';tfb.innerText='正常挂载 (FATFS)';"
"    document.getElementById('tf-cap').innerText=(res.free_mb/1024).toFixed(1)+' GB 剩余 / '+(res.total_mb/1024).toFixed(1)+' GB 总量';"
"    document.getElementById('tf-cur').innerText=res.cur_sess||'无';"
"    if(!res.files||res.files.length===0){"
"      tb.innerHTML='<tr><td colspan=\"3\" style=\"text-align:center;color:var(--sub);padding:20px;\">暂无日志文件，可点击开启全新 Session</td></tr>';"
"      return;"
"    }"
"    let h='';"
"    res.files.sort((a,b)=>b.id-a.id).forEach(f=>{"
"      const sz=f.size>1024?(f.size/1024).toFixed(1)+' KB':f.size+' B';"
"      h+='<tr><td style=\"font-family:monospace;color:#fff;\">'+f.name+'</td><td>'+sz+'</td><td>'+"
"         '<button class=\"action-btn btn-view\" onclick=\"viewLog(\\''+f.name+'\\')\">👁️ 查看</button>'+"
"         '<a class=\"action-btn btn-dl\" href=\"/api/logs/download?file='+encodeURIComponent(f.name)+'\" download>⬇️ 下载</a>'+"
"         '<button class=\"action-btn btn-del\" onclick=\"delLog(\\''+f.name+'\\')\">🗑️</button></td></tr>';"
"    });"
"    tb.innerHTML=h;"
"  }).catch(e=>{showToast('获取日志失败: '+e,'danger');});"
"}"
"function newSession(){"
"  fetch('/api/logs/new_session',{method:'POST'}).then(r=>r.json()).then(res=>{"
"    showToast('✨ 已开启新会话: '+res.file,'success');loadLogs();"
"  }).catch(e=>{showToast('新建会话失败: '+e,'danger');});"
"}"
"function delLog(name){"
"  if(!confirm('确定删除 '+name+' 吗？'))return;"
"  fetch('/api/logs/delete?file='+encodeURIComponent(name),{method:'POST'}).then(r=>r.json()).then(res=>{"
"    showToast('🗑️ 已删除 '+name,'info');loadLogs();"
"  }).catch(e=>{showToast('删除失败: '+e,'danger');});"
"}"
"function viewLog(name){"
"  document.getElementById('modal-fname').innerText=name;"
"  document.getElementById('modal-content').innerText='读取中...';"
"  document.getElementById('modal').classList.add('show');"
"  fetch('/api/logs/view?file='+encodeURIComponent(name)).then(r=>r.text()).then(txt=>{"
"    document.getElementById('modal-content').innerText=txt||'(文件内容为空)';"
"  }).catch(e=>{document.getElementById('modal-content').innerText='读取失败: '+e;});"
"}"
"function closeModal(){document.getElementById('modal').classList.remove('show');}"
"function loadFullConfig(){"
"  fetch('/api/config').then(r=>r.json()).then(c=>{"
"    if(c.sta_ssid) document.getElementById('sta-ssid').value=c.sta_ssid;"
"    if(c.sta_static_ip){"
"      document.getElementById('chk-static').checked=true;"
"      document.getElementById('static-ip-box').style.display='block';"
"      if(c.sta_ip) document.getElementById('sta-ip').value=c.sta_ip;"
"      if(c.sta_netmask) document.getElementById('sta-mask').value=c.sta_netmask;"
"      if(c.sta_gw) document.getElementById('sta-gw').value=c.sta_gw;"
"      if(c.sta_dns) document.getElementById('sta-dns').value=c.sta_dns;"
"    }"
"    if(c.ap_ssid) document.getElementById('ap-ssid-input').value=c.ap_ssid;"
"    if(c.ap_channel) document.getElementById('ap-chan').value=c.ap_channel;"
"    if(c.ap_max_conn) document.getElementById('ap-max').value=c.ap_max_conn;"
"    document.getElementById('ap-hidden').checked=!!c.ap_hidden;"
"    if(c.display_brightness){"
"      document.getElementById('cfg-bl').value=c.display_brightness;"
"      document.getElementById('val-bl').innerText=c.display_brightness;"
"    }"
"    if(c.display_timeout_s!==undefined) document.getElementById('cfg-timeout').value=c.display_timeout_s;"
"    if(c.display_rotation!==undefined) document.getElementById('cfg-rot').value=c.display_rotation;"
"    if(c.usb_default_mode!==undefined) document.getElementById('cfg-usbmode').value=c.usb_default_mode;"
"    if(c.serial_baudrate) document.getElementById('cfg-baud').value=c.serial_baudrate;"
"    if(c.serial_parity!==undefined) document.getElementById('cfg-parity').value=c.serial_parity;"
"    document.getElementById('cfg-log-en').checked=c.log_enabled!==false;"
"    if(c.log_flush_interval_ms) document.getElementById('cfg-flush').value=c.log_flush_interval_ms;"
"    if(c.log_max_file_kb!==undefined) document.getElementById('cfg-maxfile').value=c.log_max_file_kb;"
"  }).catch(()=>{});"
"}"
"function saveDisplayCfg(){"
"  const body={"
"    brightness:parseInt(document.getElementById('cfg-bl').value),"
"    timeout_s:parseInt(document.getElementById('cfg-timeout').value),"
"    rotation:parseInt(document.getElementById('cfg-rot').value)"
"  };"
"  fetch('/api/config/display',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})"
"  .then(()=>showToast('屏幕与背光设置已保存！','success')).catch(e=>showToast('保存失败: '+e,'danger'));"
"}"
"function saveSerialCfg(){"
"  const body={"
"    usb_mode:parseInt(document.getElementById('cfg-usbmode').value),"
"    baudrate:parseInt(document.getElementById('cfg-baud').value),"
"    parity:parseInt(document.getElementById('cfg-parity').value)"
"  };"
"  fetch('/api/config/serial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})"
"  .then(()=>showToast('串口与USB模式已保存！','success')).catch(e=>showToast('保存失败: '+e,'danger'));"
"}"
"function saveLoggerCfg(){"
"  const body={"
"    enabled:document.getElementById('cfg-log-en').checked,"
"    flush_ms:parseInt(document.getElementById('cfg-flush').value),"
"    max_file_kb:parseInt(document.getElementById('cfg-maxfile').value)"
"  };"
"  fetch('/api/config/logger',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})"
"  .then(()=>showToast('TF日志参数已保存！','success')).catch(e=>showToast('保存失败: '+e,'danger'));"
"}"
"function loadSysInfo(){"
"  fetch('/api/system/info').then(r=>r.json()).then(info=>{"
"    document.getElementById('sys-cpu').innerText=info.cpu||'ESP32-S3 @ 240MHz (LX7 双核)';"
"    document.getElementById('sys-flash').innerText=info.flash_size_mb+' MB (4MB App 分区)';"
"    document.getElementById('sys-heap').innerText=(info.free_heap/1024).toFixed(1)+' KB';"
"    document.getElementById('sys-minheap').innerText=(info.min_free_heap/1024).toFixed(1)+' KB';"
"    document.getElementById('sys-uptime').innerText=info.uptime_str||(Math.floor(info.uptime_s/60)+' 分钟');"
"    if(info.sta_mac) document.getElementById('sta-mac').innerText=info.sta_mac;"
"    if(info.ap_mac) document.getElementById('ap-mac').innerText=info.ap_mac;"
"  }).catch(()=>{});"
"}"
"function doReboot(){"
"  if(!confirm('确定重启 ESP32-S3 吗？'))return;"
"  fetch('/api/system/reboot',{method:'POST'}).then(()=>{showToast('正在重启... 屏幕即将刷新','info');});"
"}"
"function doDownloadMode(){"
"  if(!confirm('确定令 ESP32-S3 进入 ROM 下载模式？\\n进入后无需按 BOOT 键即可直接烧录固件。'))return;"
"  fetch('/api/system/download_mode',{method:'POST'}).then(()=>{showToast('已进入下载模式，现可直接烧录！','info');});"
"}"
"function doFactoryReset(){"
"  if(!confirm('警告：此操作将清空所有配置并恢复出厂默认值，确认继续吗？'))return;"
"  fetch('/api/system/factory_reset',{method:'POST'}).then(()=>{showToast('正在清除配置并恢复出厂...','danger');});"
"}"
"fetch('/api/wifi/status').then(r=>r.json()).then(st=>{"
"  if(st.state==='CONNECTED'){"
"    document.getElementById('net-ip').innerText=st.ip;"
"    document.getElementById('net-ssid').innerText=st.ssid;"
"    document.getElementById('net-badge').className='badge badge-sta';"
"    document.getElementById('net-badge').innerText='STA 在线';"
"  }"
"  if(st.sta_mac) document.getElementById('sta-mac').innerText=st.sta_mac;"
"  if(st.ap_mac) document.getElementById('ap-mac').innerText=st.ap_mac;"
"});"
"</script>"
"</body>"
"</html>";
