#pragma once

static const char INDEX_HTML[] = 
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<title>ESP32-S3-GEEK 极客无线调试终端</title>"
"<style>"
":root{--bg:#090d16;--card:#131b2e;--primary:#0284c7;--accent:#38bdf8;--text:#f1f5f9;--sub:#94a3b8;--border:#1e293b;--success:#10b981;--danger:#ef4444;--purple:#a855f7;}"
"*{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;}"
"body{background:var(--bg);color:var(--text);display:flex;justify-content:center;align-items:center;min-height:100vh;padding:16px;}"
".container{width:100%;max-width:480px;background:var(--card);border:1px solid var(--border);border-radius:16px;padding:24px;box-shadow:0 20px 40px rgba(0,0,0,0.6);}"
".header{display:flex;align-items:center;gap:12px;margin-bottom:16px;border-bottom:1px solid var(--border);padding-bottom:16px;}"
".icon{width:42px;height:42px;background:linear-gradient(135deg,#0284c7,#a855f7);border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:bold;font-size:22px;}"
".title h1{font-size:18px;font-weight:600;color:#fff;}"
".title p{font-size:12px;color:var(--sub);margin-top:2px;}"
".tabs{display:flex;gap:8px;margin-bottom:18px;background:#0b1120;padding:4px;border-radius:10px;border:1px solid var(--border);}"
".tab-btn{flex:1;padding:8px 12px;background:none;border:none;color:var(--sub);border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;transition:all .2s;}"
".tab-btn.active{background:var(--primary);color:#fff;box-shadow:0 2px 8px rgba(2,132,199,0.4);}"
".tab-content{display:none;}"
".tab-content.active{display:block;}"
".status-box{background:#0b1120;border:1px solid var(--border);border-radius:10px;padding:12px;margin-bottom:16px;font-size:13px;display:flex;flex-direction:column;gap:6px;}"
".status-row{display:flex;justify-content:space-between;align-items:center;}"
".badge{padding:2px 8px;border-radius:99px;font-size:11px;font-weight:600;}"
".badge-ap{background:#0369a1;color:#e0f2fe;}"
".badge-sta{background:#047857;color:#d1fae5;}"
".badge-purple{background:#7e22ce;color:#f3e8ff;}"
".badge-fail{background:#b91c1c;color:#fee2e2;}"
".form-group{margin-bottom:14px;}"
"label{display:block;font-size:13px;color:var(--sub);margin-bottom:6px;}"
"input,select{width:100%;padding:10px 14px;background:#0b1120;border:1px solid var(--border);border-radius:8px;color:#fff;font-size:14px;outline:none;transition:border-color .2s;}"
"input:focus,select:focus{border-color:var(--accent);}"
".btn{width:100%;padding:11px;background:var(--primary);color:#fff;border:none;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;transition:all .2s;display:flex;justify-content:center;align-items:center;gap:6px;}"
".btn:hover{background:#0369a1;}"
".btn:disabled{opacity:0.6;cursor:not-allowed;}"
".btn-scan{background:#1e293b;color:var(--accent);border:1px solid #334155;margin-bottom:12px;padding:8px;font-size:13px;}"
".btn-purple{background:var(--purple);}"
".btn-purple:hover{background:#9333ea;}"
".log-table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px;}"
".log-table th,.log-table td{padding:10px 8px;text-align:left;border-bottom:1px solid var(--border);}"
".log-table th{color:var(--sub);font-weight:500;font-size:12px;}"
".action-btn{padding:4px 8px;border-radius:6px;font-size:11px;font-weight:600;cursor:pointer;text-decoration:none;border:none;display:inline-block;margin-right:4px;}"
".btn-dl{background:#0284c7;color:#fff;}"
".btn-view{background:#334155;color:#e2e8f0;}"
".btn-del{background:#991b1b;color:#fecaca;}"
".modal{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.7);z-index:99;justify-content:center;align-items:center;padding:16px;}"
".modal.show{display:flex;}"
".modal-card{width:100%;max-width:600px;background:var(--card);border:1px solid var(--border);border-radius:14px;padding:18px;max-height:85vh;display:flex;flex-direction:column;}"
".modal-title{font-size:15px;font-weight:600;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center;}"
".modal-body{background:#0b1120;border:1px solid var(--border);border-radius:8px;padding:12px;overflow-y:auto;flex:1;font-family:monospace;font-size:12px;white-space:pre-wrap;color:#38bdf8;line-height:1.4;max-height:55vh;}"
".close-btn{background:none;border:none;color:var(--sub);font-size:18px;cursor:pointer;}"
".toast{padding:10px;border-radius:8px;font-size:13px;margin-top:14px;display:none;text-align:center;}"
".toast.show{display:block;}"
".toast-info{background:#075985;color:#e0f2fe;}"
".toast-success{background:#065f46;color:#d1fae5;}"
".toast-danger{background:#991b1b;color:#fee2e2;}"
".footer{margin-top:20px;text-align:center;font-size:12px;color:var(--sub);}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<div class='header'>"
"<div class='icon'>⚡</div>"
"<div class='title'>"
"<h1>ESP32-S3-GEEK</h1>"
"<p>无线调试器 · 控制台管理门户</p>"
"</div>"
"</div>"

"<div class='tabs'>"
"<button class='tab-btn active' onclick='switchTab(\"wifi\")'>📶 Wi-Fi 配网</button>"
"<button class='tab-btn' onclick='switchTab(\"logs\")'>💾 TF 卡会话日志</button>"
"</div>"

"<!-- Wi-Fi 设置选项卡 -->"
"<div id='tab-wifi' class='tab-content active'>"
"<div class='status-box'>"
"<div class='status-row'><span>工作模式:</span><span id='status-badge' class='badge badge-ap'>AP 配网热点</span></div>"
"<div class='status-row'><span>当前 IP:</span><span id='cur-ip' style='color:var(--accent);font-family:monospace;'>192.168.4.1</span></div>"
"<div class='status-row'><span>已连接热点:</span><span id='cur-ssid' style='color:#fff;'>未连接</span></div>"
"</div>"
"<button class='btn btn-scan' id='btn-scan' onclick='scanWifi()'>🔍 扫描周边 Wi-Fi 信号</button>"
"<div class='form-group'>"
"<label>选择 Wi-Fi (SSID)</label>"
"<select id='ssid-select' onchange='onSelectSSID(this.value)'>"
"<option value=''>-- 点击上方按钮扫描或手动输入 --</option>"
"</select>"
"</div>"
"<div class='form-group'>"
"<label>目标 SSID</label>"
"<input type='text' id='ssid' placeholder='输入要连入的 Wi-Fi 名称'>"
"</div>"
"<div class='form-group'>"
"<label>Wi-Fi 密码</label>"
"<input type='password' id='pwd' placeholder='输入目标 Wi-Fi 密码'>"
"</div>"
"<button class='btn' id='btn-connect' onclick='connectWifi()'>🚀 保存并连接</button>"
"</div>"

"<!-- TF 卡日志选项卡 -->"
"<div id='tab-logs' class='tab-content'>"
"<div class='status-box'>"
"<div class='status-row'><span>TF 卡状态:</span><span id='tf-badge' class='badge badge-purple'>检测中...</span></div>"
"<div class='status-row'><span>存储空间:</span><span id='tf-cap' style='color:var(--accent);font-family:monospace;'>-- / --</span></div>"
"<div class='status-row'><span>当前记录会话:</span><span id='tf-cur' style='color:#fff;'>--</span></div>"
"</div>"
"<div style='display:flex;gap:8px;margin-bottom:12px;'>"
"<button class='btn btn-purple' style='flex:2;' onclick='newSession()'>➕ 开启全新 Session</button>"
"<button class='btn' style='flex:1;background:#334155;' onclick='loadLogs()'>🔄 刷新</button>"
"</div>"
"<div style='max-height:260px;overflow-y:auto;border:1px solid var(--border);border-radius:8px;'>"
"<table class='log-table'>"
"<thead><tr><th>文件</th><th>大小</th><th>操作</th></tr></thead>"
"<tbody id='log-tbody'><tr><td colspan='3' style='text-align:center;color:var(--sub);'>正在读取 TF 卡...</td></tr></tbody>"
"</table>"
"</div>"
"</div>"

"<div class='toast' id='toast'></div>"
"<div class='footer'><p>ESP32-S3-GEEK Wireless Console Tool</p></div>"
"</div>"

"<!-- 日志查看弹窗 -->"
"<div class='modal' id='modal' onclick='closeModal(event)'>"
"<div class='modal-card' onclick='event.stopPropagation()'>"
"<div class='modal-title'><span id='modal-fname'>session.log</span><button class='close-btn' onclick='closeModal()'>&times;</button></div>"
"<div class='modal-body' id='modal-content'>读取中...</div>"
"</div>"
"</div>"

"<script>"
"function showToast(msg,type){const t=document.getElementById('toast');t.className='toast toast-'+type+' show';t.innerText=msg;setTimeout(()=>t.className='toast',4000);}"
"function switchTab(name){"
"  document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));"
"  document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));"
"  if(name==='wifi'){"
"    document.querySelectorAll('.tab-btn')[0].classList.add('active');"
"    document.getElementById('tab-wifi').classList.add('active');"
"  }else{"
"    document.querySelectorAll('.tab-btn')[1].classList.add('active');"
"    document.getElementById('tab-logs').classList.add('active');"
"    loadLogs();"
"  }"
"}"
"function onSelectSSID(val){if(val){document.getElementById('ssid').value=val;document.getElementById('pwd').focus();}}"
"function scanWifi(){"
"  const b=document.getElementById('btn-scan');b.disabled=true;b.innerText='⏳ 正在扫描 2.4G Wi-Fi...';"
"  fetch('/api/wifi/scan').then(r=>r.json()).then(data=>{"
"    b.disabled=false;b.innerText='🔍 重新扫描';"
"    const s=document.getElementById('ssid-select');s.innerHTML='<option value=\"\">-- 请选择已发现的网络 --</option>';"
"    data.forEach(item=>{"
"      const opt=document.createElement('option');opt.value=item.ssid;opt.innerText=item.ssid+' ('+item.rssi+' dBm)';"
"      s.appendChild(opt);"
"    });"
"  }).catch(e=>{"
"    b.disabled=false;b.innerText='🔍 扫描失败，点击重试';"
"    showToast('扫描超时或失败: '+e,'danger');"
"  });"
"}"
"function connectWifi(){"
"  const ssid=document.getElementById('ssid').value.trim();"
"  const pwd=document.getElementById('pwd').value;"
"  if(!ssid){showToast('请输入或选择 Wi-Fi 名称','danger');return;}"
"  const btn=document.getElementById('btn-connect');btn.disabled=true;btn.innerText='正在连接目标路由...';"
"  showToast('配置已提交，ESP32 正在尝试连接... 请观察板载屏幕','info');"
"  fetch('/api/wifi/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ssid,password:pwd})})"
"  .then(r=>r.json()).then(res=>{pollStatus();}).catch(e=>{"
"    showToast('提交失败: '+e,'danger');btn.disabled=false;btn.innerText='🚀 保存并连接';"
"  });"
"}"
"function pollStatus(){"
"  let count=0;"
"  const timer=setInterval(()=>{"
"    count++;"
"    fetch('/api/wifi/status').then(r=>r.json()).then(st=>{"
"      if(st.state==='CONNECTED'){"
"        clearInterval(timer);"
"        showToast('🎉 连接成功！分配 IP: '+st.ip,'success');"
"        document.getElementById('cur-ip').innerText=st.ip;"
"        document.getElementById('cur-ssid').innerText=st.ssid;"
"        document.getElementById('status-badge').className='badge badge-sta';"
"        document.getElementById('status-badge').innerText='STA 已连入局域网';"
"        document.getElementById('btn-connect').disabled=false;document.getElementById('btn-connect').innerText='🚀 重新配置';"
"      }else if(st.state==='FALLBACK'){"
"        clearInterval(timer);"
"        showToast('⚠️ 连接失败，已回退至 AP 模式！','danger');"
"        document.getElementById('btn-connect').disabled=false;document.getElementById('btn-connect').innerText='🚀 重新连接';"
"      }"
"    });"
"    if(count>20){clearInterval(timer);document.getElementById('btn-connect').disabled=false;}"
"  },1500);"
"}"
"function loadLogs(){"
"  fetch('/api/logs/list').then(r=>r.json()).then(res=>{"
"    const tb=document.getElementById('log-tbody');"
"    const tfb=document.getElementById('tf-badge');"
"    if(!res.mounted){"
"      tfb.className='badge badge-fail';tfb.innerText='未插入 TF 卡';"
"      document.getElementById('tf-cap').innerText='--';"
"      document.getElementById('tf-cur').innerText='--';"
"      tb.innerHTML='<tr><td colspan=\"3\" style=\"text-align:center;color:var(--sub);padding:20px;\">未检测到 MicroSD 卡，请插入后刷新</td></tr>';"
"      return;"
"    }"
"    tfb.className='badge badge-purple';tfb.innerText='正常挂载 (FATFS)';"
"    document.getElementById('tf-cap').innerText=(res.free_mb/1024).toFixed(1)+' GB 剩余 / '+(res.total_mb/1024).toFixed(1)+' GB 总量';"
"    document.getElementById('tf-cur').innerText=res.cur_sess||'无';"
"    if(!res.files||res.files.length===0){"
"      tb.innerHTML='<tr><td colspan=\"3\" style=\"text-align:center;color:var(--sub);padding:20px;\">暂无日志文件，可点击开启全新 Session</td></tr>';"
"      return;"
"    }"
"    let h='';"
"    res.files.sort((a,b)=>b.id-a.id).forEach(f=>{"
"      const sz=f.size>1024?(f.size/1024).toFixed(1)+' KB':f.size+' B';"
"      h+='<tr><td style=\"font-family:monospace;color:#fff;\">'+f.name+'</td><td>'+sz+'</td><td>'+"
"         '<button class=\"action-btn btn-view\" onclick=\"viewLog(\\''+f.name+'\\')\">👁️ 查看</button>'+"
"         '<a class=\"action-btn btn-dl\" href=\"/api/logs/download?file='+encodeURIComponent(f.name)+'\" download>⬇️ 下载</a>'+"
"         '<button class=\"action-btn btn-del\" onclick=\"delLog(\\''+f.name+'\\')\">🗑️</button></td></tr>';"
"    });"
"    tb.innerHTML=h;"
"  }).catch(e=>{showToast('获取日志失败: '+e,'danger');});"
"}"
"function newSession(){"
"  fetch('/api/logs/new_session',{method:'POST'}).then(r=>r.json()).then(res=>{"
"    showToast('✨ 已开启新会话: '+res.file,'success');loadLogs();"
"  }).catch(e=>{showToast('新建会话失败: '+e,'danger');});"
"}"
"function delLog(name){"
"  if(!confirm('确定删除 '+name+' 吗？'))return;"
"  fetch('/api/logs/delete?file='+encodeURIComponent(name),{method:'POST'}).then(r=>r.json()).then(res=>{"
"    showToast('🗑️ 已删除 '+name,'info');loadLogs();"
"  }).catch(e=>{showToast('删除失败: '+e,'danger');});"
"}"
"function viewLog(name){"
"  document.getElementById('modal-fname').innerText=name;"
"  document.getElementById('modal-content').innerText='读取中...';"
"  document.getElementById('modal').classList.add('show');"
"  fetch('/api/logs/view?file='+encodeURIComponent(name)).then(r=>r.text()).then(txt=>{"
"    document.getElementById('modal-content').innerText=txt||'(文件内容为空)';"
"  }).catch(e=>{"
"    document.getElementById('modal-content').innerText='读取失败: '+e;"
"  });"
"}"
"function closeModal(e){document.getElementById('modal').classList.remove('show');}"
"fetch('/api/wifi/status').then(r=>r.json()).then(st=>{"
"  if(st.state==='CONNECTED'){"
"    document.getElementById('cur-ip').innerText=st.ip;"
"    document.getElementById('cur-ssid').innerText=st.ssid;"
"    document.getElementById('status-badge').className='badge badge-sta';"
"    document.getElementById('status-badge').innerText='STA 在线';"
"  }"
"});"
"</script>"
"</body>"
"</html>";
